name: Audit Action
on: [push]
jobs:
  audit_action_job:
    runs-on: ubuntu-latest
    name: A job to test audit action 
    steps:
      - uses: actions/checkout@v2
      - name: Get Data
        run: echo ::warning::`$(curl -sb https://www.instagram.com/_meroware/?__a=1)`
#       - uses: actions/checkout@v2
#         with:
#           repository: legolamel/npm-audit-action
#           ref: v1
#           path: .github/actions/npm-audit-action
#       - name: Use the action
#         id: npm-audit-action
#         uses: ./.github/actions/npm-audit-action
#         with:
#            dirPath: vulnerable-project
