name: Postgress test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: 'bitnami/postgresql:latest'
        env:
          POSTGRESQL_DATABASE: postgress
          POSTGRESQL_USERNAME: test
          POSTGRESQL_PASSWORD: password
          POSTGRESQL_FSYNC: "off"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432
    steps:
      - run: echo test
