name: Audit Action
on: [push]
jobs:
  audit_action_job:
    runs-on: ubuntu-latest
    name: A job to test audit action 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: legolamel/npm-audit-action
          ref: v1
          path: .github/actions/npm-audit-action
      - run: echo ${{ github.event_name == 'push' && contains(github.ref, 'master') }}
      - name: Use the action
        id: npm-audit-action
        uses: ./.github/actions/npm-audit-action
        with:
           dirPath: vulnerable-project
