on: [push]
jobs:
  audit_action_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/audit-action@v1.0.2
      - name: Use the action
        uses: ./ # Uses an action in the root directory
        id: audit-action
        with:
          dirPath: 'vulnerable-project'