name: Audit Action
on: [push]
jobs:
  audit_action_job:
    runs-on: ubuntu-latest
    name: A job to test audit action 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: legolamel/audit-action
          ref: v1
      - name: Use the action
        id: audit-action
        uses: ./ # Uses an action in the root directory
        with:
          dirPath: vulnerable-project
          debug: true