name: Audit Action
on: [push]
jobs:
  audit_action_job:
    runs-on: ubuntu-latest
    name: A job to test audit action 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: legolamel/npm-audit-action
          ref: v1
          path: .github/actions/npm-audit-action
      - name: Run file with timeout
        id: longrunner
        continue-on-error: true
        timeout-minutes: 1 # Times out after 1 minute
        run: sleep 90 || echo 'echo "::set-output name=failure_reason::Script failed due to something random"' # Set your output error if your script fails. Include useful message
      - name: check previuos step
        run: "[ -n '${{ steps.longrunner.outputs.failure_reason }}' ] &&  echo '::error::${{ steps.longrunner.outputs.failure_reason }}' && exit 1"
      - name: Use the action
        id: npm-audit-action
        uses: ./.github/actions/npm-audit-action
        with:
           dirPath: vulnerable-project
