name: Postgress test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: 'bitnami/postgresql:latest'
        env:
          POSTGRESQL_DATABASE: test_postgress
          POSTGRESQL_USERNAME: test_user
          POSTGRESQL_PASSWORD: test_password
          POSTGRESQL_FSYNC: "off"
        options: >-
          --health-cmd pg_isready -d test_postgress -U test_user -p 5432
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - run: echo test
