name: Notify Slack Action
on: [push]
jobs:
  notify_slack_job:
    runs-on: ubuntu-latest
    name: A job to test notify slack action
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: legolamel/notify-slack-action
          ref: master
          path: .github/actions/notify-slack-action
      - id: 'test_id'
        run: 'ls'
      - name: Use the action
        if: ${{ always() }}
        id: notify-slack-action
        uses: ./.github/actions/notify-slack-action
        with:
           slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
           workflow-status: ${{ steps.test_id.outcome }}